version: "3"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
#    ports:
#      - "5430:5432"
#    restart: always
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 15s
      retries: 5

  app:
    build: .
#      context: .
#      dockerfile: Dockerfile
    tty: true
#    env_file:
#      - .env
    ports:
      - "8001:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
