services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 15s
      retries: 5
  app:
    build: .
    tty: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - .:/app
    depends_on:
      - postgres_db

volumes:
  pgdata:
