# Generated by Django 5.0.4 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='child_tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
    ]
