# Generated by Django 5.0.4 on 2024-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child_tasks',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.task'),
        ),
    ]
